 
/*
 * This file was automatically generated by EvoSuite (adapted)
 */

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EvoSuiteRegressionTest extends EvoSuiteTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Stack stack0 = new Stack(430);
      stack0.push(0);
      int int0 = stack0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Stack stack0 = new Stack(20);
      stack0.push(20);
      int int0 = stack0.pop();
      assertTrue(stack0.isEmpty());
      assertEquals(20, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Stack stack0 = new Stack(2008);
      stack0.push(2008);
      stack0.push(0);
      stack0.pop();
      int int0 = stack0.peek();
      assertEquals(1, stack0.size());
      assertEquals(2008, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Stack stack0 = new Stack(3820);
      stack0.push((-1));
      int int0 = stack0.peek();
      assertEquals(1, stack0.size());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Stack stack0 = null;
      try {
        stack0 = new Stack((-3537));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Stack", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack stack0 = new Stack(2008);
      stack0.push(0);
      boolean boolean0 = stack0.isEmpty();
      assertEquals(1, stack0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Stack stack0 = new Stack(430);
      stack0.push(0);
      int int0 = stack0.peek();
      assertEquals(1, stack0.size());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack stack0 = new Stack(430);
      int int0 = stack0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Stack stack0 = new Stack(0);
      boolean boolean0 = stack0.isFull();
      assertTrue(boolean0);
  }

    @Test(timeout = 4000)
    public void test09()  throws Throwable  {
            Stack stack0 = new Stack(3794);
            boolean boolean0 = stack0.isFull();
            assertFalse(boolean0);
            assertEquals(0, stack0.size());
    }

    @Test(timeout = 4000)
    public void test10()  throws Throwable  {
            Stack stack0 = new Stack(1639);
            stack0.push((-1));
            stack0.pop();
            boolean boolean0 = stack0.isEmpty();
            assertEquals(0, stack0.size());
            assertTrue(boolean0);
    }

    @Test(timeout = 4000)
    public void test11()  throws Throwable  {
            Stack stack0 = new Stack(1112);
            // Undeclared exception!
            try { 
                stack0.peek();
                fail("Expecting exception: IllegalStateException");
      
            } catch(IllegalStateException e) {
                 //
                 // Stack is empty
                 //
                 verifyException("Stack", e);
            }
    }

    @Test(timeout = 4000)
    public void test12()  throws Throwable  {
            Stack stack0 = new Stack(0);
            // Undeclared exception!
            try { 
                stack0.pop();
                fail("Expecting exception: IllegalStateException");
      
            } catch(IllegalStateException e) {
                 //
                 // Stack is empty
                 //
                 verifyException("Stack", e);
            }
    }

    @Test(timeout = 4000)
    public void test13()  throws Throwable  {
            Stack stack0 = new Stack(0);
            // Undeclared exception!
            try { 
                stack0.push(0);
                fail("Expecting exception: IllegalStateException");
      
            } catch(IllegalStateException e) {
                 //
                 // Stack is full
                 //
                 verifyException("Stack", e);
            }
    }

    @Test(timeout = 4000)
    public void test14()  throws Throwable  {
            Stack.main((String[]) null);
    }

}
